import "./globals.css";
import { cellular, wifi, battery, lock, toast_ok,db } from "@/app/ui/icons";
import { getAdapterName } from "./actions";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function StatusBar() {
  return (
    // TODO backdrop-filter: blur(6px);
    <div className="flex flex-row relative justify-between items-end w-375 h-52 gap-233 pt-25 pr-14 pb-15 pl-34 left-0 top-0">
      <span className="text-black w- m-0 pt-1.56 pr-0.875 pb-0.94 pl-2.125">9:41</span>
      <div className="flex flex-row gap-5 justify-center w-66.6 h-12 m-0 items-center p-0 gap-0.3125">
        <div className="w-17 h-10">{cellular}</div>
        <div className="w-17 h-10">{wifi}</div>
        <div className="w-17 h-10">{battery}</div>
      </div>
    </div>
  )
}

function BottonBar() {
  return (
    <div className="flex shadow-button-bar flex-col bg-[#f8f8f8] justify-between items-center pt-3.5 px-30 pb-2 gap-10 h-52 p-4 left-0 right-0 bottom-0 bg-[#f8f8f8]/[.82]">
      <div className="flex flex-col items-center m-auto m-0 p-0 h-30 gap-14">
        <div className="flex flex-row w-97 h-12 justify-center items-center p-0 gap-5 h-11 w-107">
          <div className="flex justify-center items-center h-[0.6875rem]">{lock}</div>
          <span className="font-normal text-xs leading-none text-gray-600">admin.feetfy.com</span>
        </div>
        <div className="w-135 h-5 bg-black rounded-full order-1"></div>
      </div>
    </div>
  )
}


export default async function RootLayout({ children }) {

  const adapterName = await getAdapterName()

  return (
    <html lang="en">
      <body>
        <div className="flex flex-col border-[0.5px] border-grey justify between mx-auto max-w-md w-375 h-[830px] bg-gray-50 py-8 left-0 top-52 gap-1 ">
          <StatusBar />
          {children}
          <BottonBar />
        </div>
        <div className="flex flex-row px-[8px] items-center border-[0.5px] border-gray justify between mx-auto max-w-md w-375 mt-[8px] bg-gray-50 py-8 left-0 top-52 gap-3">
          {db}
          <span className="text-[#0e1823] text-sm leading-[120%]">{`Current Adapter: ${adapterName}`}</span>
        </div>
      </body>
    </html >
  );
}

import React from 'react';


